version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      ESLint:
        patterns: ["*eslint*"]
    ignore:
      # Ignore dependencies that must be aligned to Kaoto UI version
      - dependency-name: "@kaoto/*"
      - dependency-name: "@kie-tools-core/*"
      - dependency-name: "@patternfly/*"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "*-browserify"
      - dependency-name: "*-loader"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
