compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@patternfly/react-code-editor@*":
    peerDependencies:
      monaco-editor: ">=0.21.0 <1"
  uniforms-bridge-json-schema@*:
    dependencies:
      react: ^18.2.0

plugins:
  - path: .yarn/plugins/plugin-list.js

yarnPath: .yarn/releases/yarn-4.4.1.cjs
