nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/plugin-list.js

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "uniforms-bridge-json-schema@*":
    dependencies:
      "react": "^18.2.0"

  "@patternfly/react-code-editor@*":
    peerDependencies:
      "monaco-editor": ">=0.21.0 <1"
