name: Test JSON Reports
description: Uploads test JSON reports to GitHub Actions

runs:
  using: composite
  steps:
    - name: Upload Test Reports
      uses: dorny/test-reporter@v2.5.0
      if: ${{ always() && !cancelled() }}
      with:
        name: UI Tests
        path: reports/ui-test-results.json
        reporter: mocha-json
