apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: integration
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: aws-ddb-streams-source
      kind: Kamelet
  steps:
  - ref:
      apiVersion: camel.apache.org/v1alpha1
      name: avro-deserialize-action
      kind: Kamelet
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: aws-translate-action
      kind: Kamelet
